Description: Tables
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  UserTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions: 
        - AttributeName: "Id"
          AttributeType: "S"
        - AttributeName: "Key"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "Id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "KeyLookup"
          KeySchema: 
            - AttributeName: "Key"
              KeyType: "HASH"
          Projection: 
            ProjectionType: "ALL"
 
Outputs:
  UserTableName:
    Description: "UserTableName"
    Value: !Ref UserTable
    Export:
      Name: UserManagerApp-UserTableName

  UserTableArn:
    Description: "UserTableArn"
    Value: !GetAtt UserTable.Arn
    Export:
      Name: UserManagerApp-UserTableArn
